spring.application.name=expenceTracker
spring.datasource.url=jdbc:mysql://localhost:3306/expenseTracker
spring.dataSource.username=Username
spring.datasource.password=Your_Password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
